"""Pure validation helpers for the K200MQ strategy."""

from k200_mq.validation.prepared import (
    PreparedK200MQInputs,
    execute_engine_interval,
)
from k200_mq.validation.walk_forward import (
    BASE_CANDIDATE,
    CANDIDATE_LIBRARY,
    CANDIDATE_LIBRARY_VERSION,
    DEFAULT_CANDIDATE_LIBRARY,
    DEFAULT_MIN_EXITS,
    EXPANDING_WINDOW_FOLDS,
    MECHANICAL_EXPANDING_WALK_FORWARD_NON_PIT,
    VALIDATED_EXPANDING_WALK_FORWARD_PIT,
    CandidateScore,
    CandidateSpec,
    FoldSpec,
    SelectionResult,
    candidate_config_hash,
    classify_walk_forward_result,
    get_expanding_window_folds,
    get_candidate_library,
    select_candidate,
    mechanical_expanding_walk_forward_non_pit,
    validated_expanding_walk_forward_pit,
)
from k200_mq.validation.runner import (
    FoldResult,
    OOSReturnPoint,
    PITValidContext,
    TestEvaluation,
    TrainEvaluation,
    WalkForwardResult,
    orchestrate_walk_forward,
    run_true_walk_forward,
    run_walk_forward,
)

__all__ = [
    "PreparedK200MQInputs",
    "execute_engine_interval",
    "BASE_CANDIDATE",
    "CANDIDATE_LIBRARY",
    "CANDIDATE_LIBRARY_VERSION",
    "DEFAULT_CANDIDATE_LIBRARY",
    "DEFAULT_MIN_EXITS",
    "EXPANDING_WINDOW_FOLDS",
    "MECHANICAL_EXPANDING_WALK_FORWARD_NON_PIT",
    "VALIDATED_EXPANDING_WALK_FORWARD_PIT",
    "CandidateScore",
    "CandidateSpec",
    "FoldSpec",
    "SelectionResult",
    "candidate_config_hash",
    "classify_walk_forward_result",
    "get_expanding_window_folds",
    "get_candidate_library",
    "select_candidate",
    "mechanical_expanding_walk_forward_non_pit",
    "validated_expanding_walk_forward_pit",
    "FoldResult",
    "OOSReturnPoint",
    "PITValidContext",
    "TestEvaluation",
    "TrainEvaluation",
    "WalkForwardResult",
    "orchestrate_walk_forward",
    "run_true_walk_forward",
    "run_walk_forward",
]
